{% set version = "1.6.5" %}

package:
  name: hyperspy-meta
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: 040d21c40e609d6c4b7b2c9e283a5ccf398450f5996a1dc2442d29e44e03793a

build:
  number: 1

requirements:
  host:
    - python

outputs:
  - name: hyperspy-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - cython                              # [build_platform != target_platform]
        - {{ compiler('c') }}
      host:
        - cython
        - pip
        - python
        - setuptools
      run:
        - dask-core >2.1.0
        - dill
        - h5py
        - imageio
        - importlib_metadata >=3.6
        - ipyparallel
        # https://github.com/ipython/ipython/pull/13466
        - ipython !=8.0
        - matplotlib-base >=3.1.0,<3.5
        - natsort
        - numba
        - numexpr
        - numpy >=1.17.1
        - packaging
        - pint >=0.10
        - pillow >5.2  # [win]
        - prettytable
        - python
        - python-dateutil >=2.5
        - pyyaml
        - requests
        - scikit-image >=0.15
        - scipy >=1.1
        - sparse
        - sympy
        - tifffile >=2019.12.3
        - tqdm >=4.9.0
        - traits >=4.5
    test:
      requires:
        - pip
        - pytest
        - pytest-xdist
      imports:
        - hyperspy
        - hyperspy.Release
        - hyperspy._lazy_signals
        - hyperspy.api
        - hyperspy.api_nogui
        - hyperspy.axes
        - hyperspy.component
        - hyperspy.components1d
        - hyperspy.components2d
        - hyperspy.decorators
        - hyperspy.defaults_parser
        - hyperspy.events
        - hyperspy.exceptions
        - hyperspy.interactive
        - hyperspy.io
        - hyperspy.logger
        - hyperspy.model
        - hyperspy.roi
        - hyperspy.samfire
        - hyperspy.signal
        - hyperspy.signal_tools
        - hyperspy.signals
        - hyperspy.ui_registry
        - hyperspy._components
        - hyperspy._signals
        - hyperspy.datasets
        - hyperspy.docstrings
        - hyperspy.drawing
        - hyperspy.drawing._markers
        - hyperspy.drawing._widgets
        - hyperspy.external
        - hyperspy.external.astropy
        - hyperspy.external.mpfit
        - hyperspy.io_plugins
        - hyperspy.learn
        - hyperspy.misc
        - hyperspy.misc.eds
        - hyperspy.misc.eels
        - hyperspy.misc.holography
        - hyperspy.misc.io
        - hyperspy.misc.machine_learning
        - hyperspy.models
        - hyperspy.samfire_utils
        - hyperspy.samfire_utils.goodness_of_fit_tests
        - hyperspy.samfire_utils.segmenters
        - hyperspy.samfire_utils.weights
        - hyperspy.utils
      commands:
        - pip check
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        - pytest --pyargs hyperspy --dist loadfile -n 2  # [not ppc64le]

  - name: hyperspy
    build:
      # We don't need it for ppc64le and it avoid running out of time on travis
      skip: true  # [ppc64le]
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - hyperspy-gui-ipywidgets >=1.3
        - hyperspy-gui-traitsui >=1.3
        - imagecodecs
        - matplotlib
        - mrcz
        - python
        - pyusid >=0.0.7
        - scikit-learn

  - name: hyperspy-dev
    build:
      # We don't need it for ppc64le and it avoid running out of time on travis
      # and drone
      skip: true  # [ppc64le or aarch64]
    requirements:
      host:
        - python
      run:
        - cython
        - freetype >=2.9,<2.10  # [py<=38]
        - matplotlib-base >=3.1,<3.2  # [py<=38]
        - numpydoc
        - pytest
        - pytest-mpl
        - pytest-xdist
        - python
        - sphinx
        - sphinx_rtd_theme

about:
  home: https://hyperspy.org
  license: GPL-3.0-or-later
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt
  dev_url: https://github.com/hyperspy/hyperspy/
  doc_url: http://hyperspy.org/hyperspy-doc/current/user_guide/index.html

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
