{% set version = "1.6.0" %}

package:
  name: hyperspy-meta
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://github.com/francisco-dlp/hyperspy/archive/RELEASE_v1.6.tar.gz
  sha256: 3368836ec76c7e5643470be4583594559869b81184e75b1e5f5db15879e331c6

build:
  number: 0
  skip: True  # [py2k]

requirements:
  host:
    - python

outputs:
  - name: hyperspy-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - setuptools
        - cython
        - pip
      run:
        - python
        - dill
        - h5py
        - ipython
        - matplotlib-base >2.2.2
        - numpy >1.13
        - scikit-image >=0.15
        - scikit-learn
        - scipy >=1.4
        - statsmodels
        - ipyparallel
        - sympy <1.5
        - natsort
        - dask >=0.18
        - traits >=4.5
        - requests
        - tqdm >=4.9.0
        - python-dateutil >=2.5
        - pint >=0.10
        - numba
        - numexpr
        - sparse
        - pillow >5.2  # [win]
        - imageio
        - mrcz
        - ptable
        - pyyaml
        - tifffile >=2018.10.18
        - pyusid >=0.0.7
    test:
      requires:
        - pytest
        - matplotlib-base >=3.1,<3.2
        - freetype >=2.9,<2.10
        - pytest-mpl
      imports:
        - hyperspy
        - hyperspy.Release
        - hyperspy._lazy_signals
        - hyperspy.api
        - hyperspy.api_nogui
        - hyperspy.axes
        - hyperspy.component
        - hyperspy.components1d
        - hyperspy.components2d
        - hyperspy.decorators
        - hyperspy.defaults_parser
        - hyperspy.events
        - hyperspy.exceptions
        - hyperspy.interactive
        - hyperspy.io
        - hyperspy.logger
        - hyperspy.model
        - hyperspy.roi
        - hyperspy.samfire
        - hyperspy.signal
        - hyperspy.signal_tools
        - hyperspy.signals
        - hyperspy.ui_registry
        - hyperspy._components
        - hyperspy._signals
        - hyperspy.datasets
        - hyperspy.docstrings
        - hyperspy.drawing
        - hyperspy.drawing._markers
        - hyperspy.drawing._widgets
        - hyperspy.external
        - hyperspy.external.astropy
        - hyperspy.external.mpfit
        - hyperspy.io_plugins
        - hyperspy.learn
        - hyperspy.misc
        - hyperspy.misc.eds
        - hyperspy.misc.eels
        - hyperspy.misc.holography
        - hyperspy.misc.io
        - hyperspy.misc.machine_learning
        - hyperspy.models
        - hyperspy.samfire_utils
        - hyperspy.samfire_utils.goodness_of_fit_tests
        - hyperspy.samfire_utils.segmenters
        - hyperspy.samfire_utils.weights
        - hyperspy.utils
      commands:
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        - pytest --pyargs hyperspy --mpl

  - name: hyperspy
    requirements:
      host:
        - python
      run:
        - python
        - pyqt
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - hyperspy-gui-ipywidgets >=1.2
        - hyperspy-gui-traitsui >=1.2
        - matplotlib

  - name: hyperspy-dev
    requirements:
      host:
        - python
      run:
        - python
        - cython
        - pytest
        - pytest-mpl
        - freetype >=2.9,<2.10
        - matplotlib-base >=3.1,<3.2
        - numpydoc
        - sphinx
        - sphinx_rtd_theme

about:
  home: https://hyperspy.org
  license: GPL-3.0-or-later
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt
  dev_url: https://github.com/hyperspy/hyperspy/
  doc_url: http://hyperspy.org/hyperspy-doc/current/user_guide/index.html

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
