{% set version = "2.3.0" %}

package:
  name: hyperspy-meta
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: 14ceb3f66d7f2926c4a73f4a54c4f38a8a5266eb78b991c31dcaba35a67d5f78

build:
  number: 3

outputs:
  - name: hyperspy-base
    build:
      noarch: python
    script: install.sh
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=64
        - setuptools_scm >=8
      run:
        - cloudpickle
        - dask-core >=2022.9.2
        - h5py >=2.3
        - importlib-metadata >=3.6
        - jinja2
        - matplotlib-base >=3.6
        - natsort
        - numpy >=1.20
        - packaging
        - pint >=0.10
        - pooch
        - prettytable >=2.3
        - python >={{ python_min }}
        - python-dateutil >=2.5
        - pyyaml
        - requests
        - rosettasciio-base
        - scikit-image >=0.18
        - scipy >=1.6.0
        - sympy >=1.10
        - tqdm >=4.59.0
        - traits >=4.5
    test:
      requires:
        - pip
        - pooch
        - pytest
        - pytest-mpl
        - pytest-rerunfailures
        - pytest-xdist
        - python {{ python_min }}
      imports:
        - hyperspy
        - hyperspy._lazy_signals
        - hyperspy.api
        - hyperspy.axes
        - hyperspy.component
        - hyperspy.components1d
        - hyperspy.components2d
        - hyperspy.decorators
        - hyperspy.defaults_parser
        - hyperspy.events
        - hyperspy.exceptions
        - hyperspy.interactive
        - hyperspy.io
        - hyperspy.logger
        - hyperspy.model
        - hyperspy.roi
        - hyperspy.samfire
        - hyperspy.signal
        - hyperspy.signal_tools
        - hyperspy.signals
        - hyperspy.ui_registry
        - hyperspy._components
        - hyperspy._signals
        - hyperspy.data
        - hyperspy.docstrings
        - hyperspy.drawing
        - hyperspy.drawing._markers
        - hyperspy.drawing._widgets
        - hyperspy.external
        - hyperspy.external.astropy
        - hyperspy.external.mpfit
        - hyperspy.learn
        - hyperspy.misc
        - hyperspy.misc.machine_learning
        - hyperspy.models
        - hyperspy.samfire_utils
        - hyperspy.samfire_utils.goodness_of_fit_tests
        - hyperspy.samfire_utils.segmenters
        - hyperspy.samfire_utils.weights
        - hyperspy.utils
      commands:
        - pip check
        - export MPLBACKEND=agg
        # remove with next release of hyperspy (>2.3.0)
        # https://github.com/hyperspy/hyperspy/pull/3554
        - pytest --pyargs hyperspy --dist loadfile -n 2 -k "not map_values_std_isset"

  - name: hyperspy
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - dask-image
        - ipympl
        - hyperspy-gui-ipywidgets >=2.1.0
        - hyperspy-gui-traitsui >=2.1.0
        # Use numba >=0.54 to have the correct numpy pinning in conda-forge
        # https://github.com/conda-forge/numba-feedstock/pull/83
        - numba >=0.54
        - numexpr >=2.8
        - pentapy
        - pybaselines
        - pyqt
        - python >={{ python_min }}
        - scikit-learn >=1.0.1

about:
  home: https://hyperspy.org
  license: GPL-3.0-or-later
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt
  dev_url: https://github.com/hyperspy/hyperspy/
  doc_url: http://hyperspy.org/hyperspy-doc/current/user_guide/index.html

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
