{% set version = "1.7.4" %}

package:
  name: hyperspy-meta
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: fb5dda43f4af612831799c89b0a953147f6325a064d06144105e6911a30baa5d

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - python

outputs:
  - name: hyperspy-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - cython                              # [build_platform != target_platform]
        - {{ compiler('c') }}
      host:
        - cython
        - pip
        - python
        - setuptools
      run:
        - dask-core >2.11.0
        - dill
        - h5py
        - imageio
        - importlib_metadata >=3.6
        - ipyparallel
        # https://github.com/ipython/ipython/pull/13466
        - ipython !=8.0
        - jinja2
        - matplotlib-base >=3.1.3
        - natsort
        # Use numba >=0.54 to have the correct numpy pinning in conda-forge
        # https://github.com/conda-forge/numba-feedstock/pull/83
        - numba >=0.54
        - numexpr
        - numpy >=1.17.1
        - packaging
        - pint >=0.10
        - pillow >5.2  # [win]
        - prettytable
        - python
        - python-dateutil >=2.5
        - pyyaml
        - requests
        - scikit-image >=0.15
        - scipy >=1.1
        - sparse
        - sympy
        - tifffile >=2020.2.16
        - tqdm >=4.9.0
        - traits >=4.5
        - zarr >=2.9
    test:
      requires:
        - pip
        - pytest
        - pytest-xdist
      imports:
        # Skip some import on aarch64 because of packaging issue with scikit-image
        # https://github.com/conda-forge/scikit-image-feedstock/issues/93
        - hyperspy
        - hyperspy.Release
        - hyperspy._lazy_signals  # [not aarch64]
        - hyperspy.api
        - hyperspy.api_nogui
        - hyperspy.axes
        - hyperspy.component
        - hyperspy.components1d
        - hyperspy.components2d
        - hyperspy.decorators
        - hyperspy.defaults_parser
        - hyperspy.events
        - hyperspy.exceptions
        - hyperspy.interactive
        - hyperspy.io
        - hyperspy.logger
        - hyperspy.model
        - hyperspy.roi
        - hyperspy.samfire
        - hyperspy.signal
        - hyperspy.signal_tools
        - hyperspy.signals
        - hyperspy.ui_registry
        - hyperspy._components
        - hyperspy._signals  # [not aarch64]
        - hyperspy.datasets
        - hyperspy.docstrings
        - hyperspy.drawing
        - hyperspy.drawing._markers
        - hyperspy.drawing._widgets
        - hyperspy.external
        - hyperspy.external.astropy
        - hyperspy.external.mpfit
        - hyperspy.io_plugins
        - hyperspy.learn
        - hyperspy.misc
        - hyperspy.misc.eds
        - hyperspy.misc.eels
        - hyperspy.misc.holography
        - hyperspy.misc.io
        - hyperspy.misc.machine_learning
        - hyperspy.models  # [not aarch64]
        - hyperspy.samfire_utils
        - hyperspy.samfire_utils.goodness_of_fit_tests
        - hyperspy.samfire_utils.segmenters
        - hyperspy.samfire_utils.weights
        - hyperspy.utils
      commands:
        - pip check
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        # test_nonconvolved failed on linux python 3.7 (precision issue)
        # test_jeol cause memory errors on windows, to be removed in hyperspy 2.0
        - pytest --pyargs hyperspy --dist loadfile -k "not test_nonconvolved and not test_jeol" -n 2  # [not ppc64le and not aarch64]

  - name: hyperspy
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - hyperspy-gui-ipywidgets >=1.5
        - hyperspy-gui-traitsui >=1.5  # [not ppc64le]
        - imagecodecs
        - matplotlib
        - mrcz
        - python
        - pyusid >=0.0.7
        - scikit-learn

  - name: hyperspy-dev
    build:
      # We don't need it for ppc64le and it avoid running out of time on travis
      # and drone
      skip: true  # [ppc64le or aarch64]
    requirements:
      host:
        - python
      run:
        - cython
        - freetype >=2.10,<2.11
        - matplotlib-base >=3.5,<3.6
        - numpydoc
        - pytest
        - pytest-mpl
        - pytest-xdist
        - python
        - sphinx
        - sphinx_rtd_theme

about:
  home: https://hyperspy.org
  license: GPL-3.0-or-later
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt
  dev_url: https://github.com/hyperspy/hyperspy/
  doc_url: http://hyperspy.org/hyperspy-doc/current/user_guide/index.html

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
