{% set version = "2.4.0" %}

package:
  name: hyperspy-meta
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: 0c7a3b2136f690ebf7b9c0bcd8a81f89871722b732cf201f257ac07b9845d077

build:
  number: 0

outputs:
  - name: hyperspy-base
    build:
      noarch: python
    script: install.sh
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools >=64
        - setuptools_scm >=8
      run:
        - cloudpickle
        - dask-core >=2023.2.1
        - h5py
        - imageio
        - importlib-metadata >=3.6
        - jinja2
        - matplotlib-base >=3.6
        - natsort
        - numpy >=1.22.0
        - packaging
        - pillow
        - pint >=0.10
        - prettytable >=2.3
        - python >={{ python_min }}
        - pyyaml
        - rosettasciio-base >=0.12.0
        - scipy >=1.8.0
        - sympy >=1.10
        - tqdm >=4.59.0
        - traits >=6.4.0
    test:
      requires:
        - pip
        - pooch
        - pytest
        - pytest-mpl
        - pytest-rerunfailures
        - pytest-xdist
        - python {{ python_min }}
      imports:
        - hyperspy
        - hyperspy.api
        - hyperspy.axes
        - hyperspy.component
        - hyperspy.components1d
        - hyperspy.components2d
        - hyperspy.decorators
        - hyperspy.defaults_parser
        - hyperspy.events
        - hyperspy.exceptions
        - hyperspy.interactive
        - hyperspy.io
        - hyperspy.logger
        - hyperspy.model
        - hyperspy.roi
        - hyperspy.samfire
        - hyperspy.signal
        - hyperspy.signal_tools
        - hyperspy.signals
        - hyperspy.ui_registry
        - hyperspy._components
        - hyperspy.data
        - hyperspy.docstrings
        - hyperspy.drawing
        - hyperspy.drawing._markers
        - hyperspy.drawing._widgets
        - hyperspy.external
        - hyperspy.external.astropy
        - hyperspy.external.mpfit
        - hyperspy.learn
        - hyperspy.misc
        - hyperspy.misc.machine_learning
        - hyperspy.models
        - hyperspy.samfire_utils
        - hyperspy.samfire_utils.goodness_of_fit_tests
        - hyperspy.samfire_utils.segmenters
        - hyperspy.samfire_utils.weights
        - hyperspy.utils
      commands:
        - pip check
        - export MPLBACKEND=agg
        - pytest --pyargs hyperspy --dist loadfile -n 2

  - name: hyperspy
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - dask-image
        - ipympl
        - hyperspy-gui-ipywidgets >=2.1.0
        - hyperspy-gui-traitsui >=2.1.0
        - numba >=0.56.0
        - numexpr >=2.8.0
        - pentapy
        - pybaselines
        - pyqt
        - python >={{ python_min }}
        - scikit-image >=0.19
        - scikit-learn >=1.6.0

about:
  home: https://hyperspy.org
  license: GPL-3.0-or-later
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt
  dev_url: https://github.com/hyperspy/hyperspy/
  doc_url: http://hyperspy.org/hyperspy-doc/current/user_guide/index.html

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
