{% set version = "1.4" %}

package:
  name: hyperspy
  version: {{ version }}

source:
  fn: hyperspy-1.4.1.tar.gz
  # url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  url: https://github.com/francisco-dlp/hyperspy/archive/v1.4.1.tar.gz 
  sha256: 020f0ce6191d55d7ce6bbceca45ac310953416ac5eb11dd19afc8ca77d3a5c71

build:
  number: 0
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - pip
  run:
    - python
    - dill
    - h5py
    - ipython
    - jupyter
    - matplotlib >2.2.2
    - numpy >1.13
    - scikit-image >=0.13
    - scikit-learn
    - scipy >=0.15
    - statsmodels
    - ipyparallel
    - sympy
    - natsort
    - lxml
    - dask >=0.18
    - traits >=4.5
    - requests
    - tqdm >=0.4.9
    - python-dateutil >=2.5
    - backports_abc  # [py34]
    - pint >0.8
    - numba
    - numexpr
    # - hyperspy-gui-ipywidgets
    # - hyperspy-gui-traitsui
    - sparse
test:
    requires:
        - pytest
        - pytest-mpl
        - freetype 2.9.*
        - matplotlib <3.0  
        - pillow >5.2
    commands:
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        - py.test --pyargs hyperspy --mpl

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
