{% set version = "1.1.2" %}

package:
  name: hyperspy
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: 67e65ede20071bf20a88a4481e66f1be29f438c3827f82396cf955f301dc70dc 

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - dill
    - h5py
    - ipython
    - jupyter
    - matplotlib >=1.2
    - numpy
    - qt 4.8.*
    - scikit-image
    - scikit-learn
    - scipy
    - statsmodels
    - ipyparallel
    - sympy
    - natsort
    - lxml
    - dask
    - traits >=4.5
    - traitsui >=5.0
    - requests
    - ipywidgets >=5.0
    - tqdm
    - python-dateutil
    - backports_abc  # [py34]
test:
    requires:
        - nose

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
