{% set version = "1.4.1" %}

package:
  name: hyperspy-split
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: 1527bc374e539b07d64e6d95ac30b351c3e9ed0183886084b993f70c696045d9 

build:
  number: 1
  skip: True  # [py2k]

outputs:
  - name: hyperspy-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - setuptools
        - cython
        - pip
      run:
        - python
        - dill
        - h5py
        - ipython
        - jupyter
        - matplotlib >2.2.2
        - numpy >1.13
        - scikit-image >=0.13
        - scikit-learn
        - scipy >=0.15
        - statsmodels
        - ipyparallel
        - sympy
        - natsort
        - dask >=0.18
        - traits >=4.5
        - requests
        - tqdm >=0.4.9
        - python-dateutil >=2.5
        - pint >0.8
        - numba
        - numexpr
        - sparse
    test:
      requires:
        - pytest
        - matplotlib <3.0  
        - pytest-mpl
      commands:
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        - py.test --pyargs hyperspy --mpl

  - name: hyperspy
    requirements:
      run:
        - python
        - pyqt
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - hyperspy-gui-ipywidgets >=1.1
        - hyperspy-gui-traitsui >=1.1

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
