{% set version = "1.4.2" %}

package:
  name: hyperspy-meta
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://github.com/francisco-dlp/hyperspy/archive/v1.4.2.tar.gz
  sha256: f2a0cca9cd171a42a8a68ea1b42e33a3f4aa7b6bc4dbb23624b9524a5bf9f4b1

build:
  number: 0
  skip: True  # [py2k]

requirements:
  host:
    - python

outputs:
  - name: hyperspy-base
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - python
        - setuptools
        - cython
        - pip
      run:
        - python
        - dill
        - h5py
        - ipython
        - jupyter
        - matplotlib >2.2.2,<3.1
        - numpy >1.13
        - scikit-image >=0.13
        - scikit-learn
        - scipy >=0.15
        - statsmodels
        - ipyparallel
        - sympy
        - natsort
        - dask >=0.18
        - traits >=4.5
        - requests
        - tqdm >=0.4.9
        - python-dateutil >=2.5
        - pint >0.8
        - numba
        - numexpr
        - sparse
        - pillow >5.2  # [win]
    test:
      requires:
        - pytest <4.1
        - matplotlib <3.0  
        - pytest-mpl
        - xorg-libx11  # [linux]
      imports:
        - hyperspy
        - hyperspy.Release
        # - hyperspy._lazy_signals
        - hyperspy.api
        - hyperspy.api_nogui
        - hyperspy.axes
        - hyperspy.component
        - hyperspy.components1d
        - hyperspy.components2d
        - hyperspy.decorators
        - hyperspy.defaults_parser
        - hyperspy.events
        - hyperspy.exceptions
        - hyperspy.interactive
        - hyperspy.io
        - hyperspy.logger
        - hyperspy.model
        - hyperspy.roi
        - hyperspy.samfire
        - hyperspy.signal
        - hyperspy.signal_tools
        - hyperspy.signals
        - hyperspy.ui_registry
        - hyperspy._components
        - hyperspy._signals
        - hyperspy.datasets
        - hyperspy.docstrings
        - hyperspy.drawing
        - hyperspy.drawing._markers
        - hyperspy.drawing._widgets
        - hyperspy.external
        - hyperspy.external.astroML
        - hyperspy.external.mpfit
        - hyperspy.io_plugins
        - hyperspy.learn
        - hyperspy.misc
        - hyperspy.misc.eds
        - hyperspy.misc.eels
        - hyperspy.misc.holography
        - hyperspy.misc.io
        - hyperspy.misc.machine_learning
        - hyperspy.models
        - hyperspy.samfire_utils
        - hyperspy.samfire_utils.goodness_of_fit_tests
        - hyperspy.samfire_utils.segmenters
        - hyperspy.samfire_utils.weights
        - hyperspy.utils
      commands:
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        # - pytest --pyargs hyperspy --mpl
        - pytest --pyargs hyperspy

  - name: hyperspy
    requirements:
      host:
        - python
      run:
        - python
        - pyqt
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - hyperspy-gui-ipywidgets >=1.1
        - hyperspy-gui-traitsui >=1.1
        - jupyterlab >=0.35.4
        - nodejs

  - name: hyperspy-dev
    requirements:
      host:
        - python
      run:
        - python
        - cython
        - {{ pin_subpackage('hyperspy-base', exact=True) }}
        - pytest
        - pytest-mpl
        - matplotlib
        - numpydoc
        - sphinx
        - sphinx_rtd_theme

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt
  dev_url: https://github.com/hyperspy/hyperspy/
  doc_url: http://hyperspy.org/hyperspy-doc/current/user_guide/index.html

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
