{% set version = "1.1.1" %}

package:
  name: hyperspy
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://github.com/hyperspy/hyperspy/archive/RELEASE_next_patch.tar.gz 
  sha256: 7d98a5c28ed0907744eb962cb7e6a5cba6779f2a910a3643626e0ec49ff45b8a 

build:
  number: 1
  skip: True  # [py2k]
  detect_binary_files_with_prefix: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython <=0.24.1
    - numpy
  run:
    - python
    - dill
    - h5py
    - ipython
    - ipykernel <=4.5.0 # from 4.5 on one test fails (the test is fixed in hspy 1.1.2)
    - jupyter
    - matplotlib >=1.2
    - numpy
    - qt <5.0
    - scikit-image
    - scikit-learn
    - scipy
    - statsmodels
    - ipyparallel
    - sympy
    - natsort
    - lxml
    - dask
    - traits >=4.5
    - traitsui >=5.0
    - requests
    - ipywidgets >=5.0
    - tqdm
    - python-dateutil
    - backports_abc  # [py34]
test:
    requires:
        - nose

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
