{% set version = "1.2" %}

package:
  name: hyperspy
  version: {{ version }}

source:
  fn: RELEASE_v1.2.tar.gz
  url: https://github.com/francisco-dlp/hyperspy/archive/RELEASE_v1.2.tar.gz
  sha256: 3a87b3c61b68b706720ea1643043bfa15096ca003db21da992240e33225e52dc
#  fn: hyperspy-{{ version }}.tar.gz
#  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
#  sha256: 67e65ede20071bf20a88a4481e66f1be29f438c3827f82396cf955f301dc70dc 

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
    - dill
    - h5py
    - ipython
    - jupyter
    - matplotlib >=1.2
    - numpy >=1.10
    - qt 4.8.*
    - scikit-image
    - scikit-learn
    - scipy >=0.15
    - statsmodels
    - ipyparallel
    - sympy
    - natsort
    - lxml
    - dask ==0.13|>0.14
    - traits >=4.5
    - traitsui >=5.0
    - requests
    - ipywidgets >=5.0
    - tqdm
    - python-dateutil
    - backports_abc  # [py34]
test:
    requires:
        - pytest
        - pytest-mpl
    commands:
        - export MPLBACKEND="tkagg"
        - py.test --pyargs hyperspy --mpl

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
