{% set version = "1.3" %}

package:
  name: hyperspy
  version: {{ version }}

source:
  fn: hyperspy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: 00299b5673d8f14dfa12f02fbd12af636f2627f4649ec5b889509e8b682d1763 

build:
  number: 1
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
    - dill
    - h5py
    - ipython
    - jupyter
    - matplotlib >=1.2
    - numpy >=1.10
    - scikit-image >=0.13
    - scikit-learn
    - scipy >=0.15
    - statsmodels
    - ipyparallel
    - sympy
    - natsort
    - lxml
    - dask ==0.14.3
    - traits >=4.5
    - requests
    - tqdm >=0.4.9
    - python-dateutil
    - backports_abc  # [py34]
    - pint >0.7
    - numba 
    - hyperspy-gui-ipywidgets
    - numexpr

test:
    requires:
        - pytest
        - pytest-mpl
    commands:
        - export MPLBACKEND="agg"  # [unix]
        - set MPLBACKEND="agg"  # [win]
        - py.test --pyargs hyperspy --mpl

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
