{% set version = "1.3.2" %}

package:
  name: hyperspy
  version: {{ version }}

source:
  fn: hyperspy-RELEASE_v1.3.2.tar.gz
  url: https://pypi.io/packages/source/h/hyperspy/hyperspy-{{ version }}.tar.gz
  sha256: bb1fbe5665201d758b3379d6fb4362ab015b11b2203e16c1e5abcf783490b5bd 

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
  run:
    - python
    - dill
    - h5py
    - ipython
    - jupyter
    - matplotlib >2.1.1
    - numpy >=1.10
    - scikit-image >=0.13
    - scikit-learn
    - scipy >=0.15
    - statsmodels
    - ipyparallel
    - sympy
    - natsort
    - lxml
    - dask >=0.18
    - traits >=4.5
    - requests
    - tqdm >=0.4.9
    - python-dateutil >=2.5
    - backports_abc  # [py34]
    - pint >0.8
    - numba 
    - hyperspy-gui-ipywidgets
test:
    requires:
        - pytest
        - pytest-mpl
        - freetype 2.8*
    commands:
        - export MPLBACKEND=agg  # [unix]
        - set MPLBACKEND=agg  # [win]
        - py.test --pyargs hyperspy --mpl

about:
  home: https://hyperspy.org
  license: GPL v3
  summary: Multi-dimensional data analysis
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
