appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cRgTZF8wZSqPYbrLa3Qysr5d40xvJC+YwAK7h9x03JzEbCA6zTQAHji2HD5BoZcwd6ERh/FTb5Gmltzd+hGpQWtfyOSLc6ZpKv38X/vohf4pmnPkC0PLrYLDbGsSPpNrH6/xLGIGr7kAn5iD9JkKpODQizNynGPO0YiZxOd87QMfHWPJ8/QPyfj5VDE10wVoe13WE14oNIA1tIH4OXCbWaIq3yLd/yTbE3EzK2jL4HXZMNcbyJxShGmVcdvPkIbnHC5hil9LGlB8Z/ddT14Nr2g/BwKnC541gChWFxcLwy1WTyzts6gefidwiiQF9d0moJpJMHC2K+SkZnJ6GqNPqNtE2H0rP9/xjeNLOnnq/huAA556VVJVbknT8OEo5uQUhixin+4TIddF/zdMjjduwQVp/n9O8Mx22zIH44mUX6AuOH4BzaX6GL75hTopS/22ZljnzDAoWzCoGyv6jTPSaf9q7mOcig2kAE8YrDJw3VNt6kBUckK2UWNrlnRlTPiqz+cy9gzbKLRYpfUsaIQmDWNaBNE7KH+W2Br9/4E4gM8UjPLgkKOleL+ODDJ9yo+yUqi1pvIXQhY15b2BcCLEp75mwCrl4flIO/hJtbrN/sHY/45bUwaeIoN7haQ/R1ERjjF45rXWMSVqeRO5Q3wP3VNQxiPkbPZyzLsSFZgBAA0=}
