travis:
  secure:
    BINSTAR_TOKEN: s2d52C3KVEL6oMIEEeFNQeB2GTLTWqYSTtfL9UXUY297cKduNDwx+5gjcTh8ax2qozQq6WLiT4zCcoGycUZcKjCeNX7au81pV+BmOEvtk5F9U7jpMt1dCItA97LsSDBKbHvAB3uRfTX0W1k+HbhyuYsemGQvOrSyOiqJS9fGuuj2eAaOi1Qpg1prFu0+s0q0aY225bJ5LS0s+HmaacMk813uqMsi+SLS0D2Ve0GTpfrdIR33AwjrKAPyKuyQdGcbjbUW0MDQLwBMklPSySU5O1JVRct9lQ2wxtuzxkzwP7ZZvyda8miwIAOc788yc1AXcBIEiwM2j4n8mhg/o/xvBR0S+tvnp0Zt1cKI7Gq9HXiVAOj+JE+9fP6NRjcEC6CIeF5dUacBJVsGEYKWTguQo5LQtI7/Jcq0R+jZtNuzygthBT8mE8WsYnGfYUmX1JR5Hw6w5vkkFlVcOzPzy0nutlW/iM4l8PHlTqLdcO0dSMw3PcurzjbKvPz0InNQX2KzlVYlPQosHhX7r0VbyKLiVzn1zbhDfSxdJg5YhTsauWWLt8lGRLm9ylotQCdPaSkWB5R8McneUcIZd1qaAi3WF/n5UebBKvQ5dBLsHCiBUqm8u64KUw/D2aggFmyb3+StCjpOzU6p9xovAZPRRWWxcBaKYoZefTV0cPUnpX0xAKU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
